// Səviyyə imtahanları. Bölmələr: v=söz, g=qrammatika, r=oxu, l=dinləmə
// item: [tip, sual, [variantlar], düzgün indeks]
const EXAMS = {
1: {
 level:"A2", after:20, part:1, pass:75, mins:35,
 title:"A2 səviyyə imtahanı",
 intro:"Dərs 1–20-nin sözləri (1–900) və A1–A2 qrammatikası. 40 sual · 4 bölmə. 75%+ = A2 təsdiqlənir.",
 reading:{title:"Nigar's day",text:"Nigar works in a small shop in the center of Baku. She starts work at nine in the morning and finishes at six. The shop sells books and newspapers. Nigar likes her job because she meets many people every day. Some customers come every week, and she knows their names.\n\nOn Saturday the shop is very busy, but on Sunday it is closed. Nigar lives far from the shop, so she takes the bus. The bus takes forty minutes. Last month she started to learn English after work. She goes to a class two times a week. She says: \"English is not easy, but I want to read books in English one day.\""},
 listening:[
  "The meeting starts at half past nine on Monday morning.",
  "I cannot come to the party because I have to work.",
  "Please take the second street on the right, next to the bank.",
  "My sister lives in London, but my brother lives in Baku.",
  "The shop opens at eight in the morning and closes at ten in the evening."],
 items:[
  ["v","başa düşmək",["understand","remember","describe","continue"],0],
  ["v","demək olar ki",["almost","already","enough","between"],0],
  ["v","səbəb",["reason","result","reach","remain"],0],
  ["v","artıq (indiyə qədər)",["already","always","almost","again"],0],
  ["v","vacib",["important","interested","international","increase"],0],
  ["v","cavab vermək",["answer","ask","allow","appear"],0],
  ["v","qərar vermək",["decide","describe","develop","discuss"],0],
  ["v","arasında",["between","behind","beyond","before"],0],
  ["v","kifayət",["enough","early","either","every"],0],
  ["v","gözləmək (ummaq)",["expect","explain","experience","example"],0],
  ["v","növbəti",["next","near","note","never"],0],
  ["v","lakin",["however","whatever","whenever","wherever"],0],
  ["v","dəyişmək",["change","charge","choose","check"],0],
  ["v","xatırlamaq",["remember","remain","receive","return"],0],
  ["v","təklif etmək",["suggest","support","serve","send"],0],
  ["g","She ___ to school every day.",["goes","go","going","is go"],0],
  ["g","I ___ born in Baku.",["was","were","am","is"],0],
  ["g","There ___ many people here.",["are","is","be","has"],0],
  ["g","He is ___ than his brother.",["taller","tall","tallest","more tall"],0],
  ["g","___ you help me, please?",["Can","Are","Do you can","Is"],0],
  ["g","I have ___ money, but not much.",["some","any","no","many"],0],
  ["g","Yesterday I ___ to the market.",["went","go","have gone","going"],0],
  ["g","This is ___ car.",["my","mine","me","I"],0],
  ["g","She doesn't ___ coffee.",["like","likes","liked","liking"],0],
  ["g","The book is ___ the table.",["on","in","at","to"],0],
  ["g","I am interested ___ music.",["in","on","at","for"],0],
  ["g","___ is your name?",["What","Who","How","Which"],0],
  ["g","I want ___ a new phone.",["to buy","buy","buying","bought"],0],
  ["g","He has two ___.",["children","childs","childrens","child"],0],
  ["g","We are going ___ visit our friends tomorrow.",["to","for","at","in"],0],
  ["r","What does the shop sell?",["Books and newspapers","Food","Clothes","Phones"],0],
  ["r","When is the shop closed?",["On Sunday","On Saturday","On Monday","Every evening"],0],
  ["r","How does Nigar go to work?",["By bus","By car","She walks","By train"],0],
  ["r","Why does she like her job?",["She meets many people","The money is good","It is near her home","The work is easy"],0],
  ["r","How often does she go to the English class?",["Two times a week","Every day","Once a month","On Sunday"],0],
  ["l","When does the meeting start?",["9:30","9:00","8:30","10:30"],0],
  ["l","Why can he not come?",["He has to work","He is ill","He is far away","He does not want to"],0],
  ["l","Where is the street?",["Next to the bank","Behind the bank","In front of the school","Near the park"],0],
  ["l","Who lives in Baku?",["His brother","His sister","Both of them","Nobody"],0],
  ["l","How long is the shop open?",["14 hours","10 hours","12 hours","8 hours"],0]
 ]
},
2: {
 level:"A2+", after:35, part:1, pass:75, mins:40,
 title:"A2+ səviyyə imtahanı",
 intro:"Dərs 1–35-in sözləri (1–2200) və A2–B1 keçid qrammatikası. 45 sual · 4 bölmə. 75%+ = A2+ təsdiqlənir.",
 reading:{title:"A new job",text:"Murad had worked in the same office for six years when he decided to change his life. He was not unhappy, but he felt that he was not growing. Every morning he did the same work, and every evening he came home tired. His salary was enough, yet something was missing.\n\nOne evening his friend told him about a company that was looking for a project manager. The job needed good English and experience with customers. Murad had the experience, but his English was weak. He thought about it for a week. Then he sent his application and started studying English every night.\n\nThe interview was difficult. They asked him about problems he had solved and how he worked with a team. He did not understand every question, but he answered honestly. Two weeks later they offered him the position. His new salary is higher, but he says the most important change is different: now he learns something new every week."},
 listening:[
  "Although the weather was terrible, we decided to continue the journey.",
  "The manager said the report must be finished before Friday afternoon.",
  "She has been working in this company since two thousand nineteen.",
  "If you take the early train, you will arrive before the meeting starts.",
  "He apologized for the delay and promised to send the documents today."],
 items:[
  ["v","artmaq, yüksəlmək",["increase","include","indicate","introduce"],0],
  ["v","təmin etmək",["provide","prove","produce","prefer"],0],
  ["v","nəticə",["result","reason","research","record"],0],
  ["v","imkan, fürsət",["opportunity","operation","organization","opinion"],0],
  ["v","tələb etmək",["require","recognize","reduce","relate"],0],
  ["v","əhəmiyyətli",["significant","similar","simple","single"],0],
  ["v","qiymətləndirmək",["consider","continue","control","contain"],0],
  ["v","davranış",["behavior","benefit","balance","background"],0],
  ["v","müqayisə etmək",["compare","complete","compete","complain"],0],
  ["v","təsir",["effect","effort","event","example"],0],
  ["v","əlavə olaraq",["besides","because","before","between"],0],
  ["v","qaçınmaq",["avoid","allow","appear","apply"],0],
  ["v","kifayət qədər",["quite","quick","quiet","quality"],0],
  ["v","təxminən",["approximately","apparently","absolutely","actually"],0],
  ["v","məsuliyyət",["responsibility","relationship","requirement","recommendation"],0],
  ["v","üstünlük vermək",["prefer","prepare","present","prevent"],0],
  ["v","şərait, vəziyyət",["condition","conference","connection","consumer"],0],
  ["v","nail olmaq",["achieve","agree","allow","argue"],0],
  ["g","I ___ in this company for three years.",["have worked","work","worked","am working"],0],
  ["g","She said she ___ come tomorrow.",["would","will","is","was"],0],
  ["g","If it rains, we ___ at home.",["will stay","stayed","would stay","stay"],0],
  ["g","The letter ___ yesterday.",["was sent","sent","is sent","has sent"],0],
  ["g","I have lived here ___ 2020.",["since","for","from","during"],0],
  ["g","He is the man ___ helped me.",["who","which","whose","whom"],0],
  ["g","You ___ smoke here. It is forbidden.",["mustn't","don't have to","needn't","couldn't"],0],
  ["g","I am used to ___ early.",["getting up","get up","got up","gets up"],0],
  ["g","___ she was tired, she finished the work.",["Although","Because","However","Despite"],0],
  ["g","There isn't ___ milk in the fridge.",["any","some","many","few"],0],
  ["g","This is the ___ film I have ever seen.",["best","better","good","most good"],0],
  ["g","He asked me where I ___.",["lived","live","am living","do live"],0],
  ["g","I would buy that car if I ___ enough money.",["had","have","will have","would have"],0],
  ["g","The book ___ by many students.",["is read","reads","is reading","has read"],0],
  ["g","She has ___ finished her homework.",["already","yet","still","ever"],0],
  ["g","We look forward ___ from you.",["to hearing","to hear","hearing","hear"],0],
  ["g","Neither of the answers ___ correct.",["is","are","were","have"],0],
  ["r","Why did Murad want to change his job?",["He felt he was not growing","His salary was too low","He did not like his colleagues","The office was far from home"],0],
  ["r","What was the main problem for the new job?",["His English was weak","He had no experience","He was too old","The salary was lower"],0],
  ["r","How long did he think before applying?",["A week","A day","A month","Six years"],0],
  ["r","What happened in the interview?",["He did not understand everything but answered honestly","He answered every question perfectly","He refused to answer","He spoke only Azerbaijani"],0],
  ["r","What does Murad say is the most important change?",["He learns something new every week","He earns more money","He works fewer hours","He has a bigger office"],0],
  ["l","What does the speaker say about the weather?",["It was bad but they continued","It was good so they continued","They stopped because of it","They changed the date"],0],
  ["l","When must the report be finished?",["Before Friday afternoon","On Friday evening","After the weekend","Before Monday"],0],
  ["l","How long has she worked there?",["Since 2019","For two months","Since she was nineteen","For nineteen years"],0],
  ["l","What happens if he takes the early train?",["He arrives before the meeting","He misses the meeting","He arrives late","The meeting is cancelled"],0],
  ["l","What did he promise?",["To send the documents today","To come tomorrow","To pay the money","To call the manager"],0]
 ]
},
3: {
 level:"B1", after:50, part:1, pass:75, mins:45,
 title:"B1 səviyyə imtahanı",
 intro:"Pillə 1-in bütün 3000 sözü və B1 qrammatikası. 50 sual · 4 bölmə. 75%+ = B1 təsdiqlənir.",
 reading:{title:"Working from home",text:"Ten years ago, working from home was unusual in most countries. Today millions of people open their laptops in their kitchens instead of travelling to an office. The change happened quickly, and companies are still trying to understand what it means.\n\nThe advantages are obvious. Employees save the time and money they used to spend on transport. Many say they concentrate better at home, where nobody interrupts them every ten minutes. Parents can be present when their children come back from school. For companies, smaller offices mean lower costs.\n\nHowever, there are serious disadvantages as well. Some workers feel isolated and report that they miss the informal conversations that happen naturally in an office. Others find it difficult to separate work from private life: if the laptop is always on the table, the working day never really ends. Managers complain that it is harder to train new employees who have never met their colleagues face to face.\n\nMost experts now believe the future is neither one nor the other. A mixed model, in which staff come to the office two or three days a week, seems to combine the benefits of both. What is certain is that the traditional idea of spending five days a week at the same desk will not return."},
 listening:[
  "The government announced that the new regulations will come into force at the beginning of next year.",
  "Despite the increase in prices, demand for the product has remained surprisingly stable.",
  "She explained that the project had been delayed because two members of the team resigned.",
  "According to the research, students who sleep eight hours perform significantly better in examinations.",
  "The company is considering opening a second office, although no final decision has been made yet."],
 items:[
  ["v","həyata keçirmək, tətbiq etmək",["implement","imply","improve","impress"],0],
  ["v","əldə etmək",["obtain","observe","occupy","occur"],0],
  ["v","mövcud olmaq",["exist","expand","expect","express"],0],
  ["v","əvəz etmək",["replace","represent","require","research"],0],
  ["v","fərz etmək",["assume","assist","assign","assess"],0],
  ["v","əhatə dairəsi",["scope","scale","source","stage"],0],
  ["v","davamlı, dayanıqlı",["sustainable","substantial","subsequent","sufficient"],0],
  ["v","nəzərə çarpan dərəcədə",["significantly","similarly","simply","sincerely"],0],
  ["v","güzəştə getmək",["compromise","complain","compete","complete"],0],
  ["v","öhdəsindən gəlmək",["overcome","overlook","observe","obtain"],0],
  ["v","qərəz, meyl",["bias","basis","benefit","barrier"],0],
  ["v","təcrid etmək",["isolate","illustrate","indicate","involve"],0],
  ["v","əvvəlcədən görmək",["anticipate","announce","analyze","apply"],0],
  ["v","qaçılmaz nəticə",["consequence","conference","confidence","condition"],0],
  ["v","dəqiqləşdirmək",["specify","simplify","satisfy","separate"],0],
  ["v","etibarlı",["reliable","reasonable","remarkable","responsible"],0],
  ["v","aşkar, açıq-aydın",["obvious","occasional","official","optional"],0],
  ["v","müdaxilə etmək",["interrupt","interpret","introduce","invest"],0],
  ["v","davam etdirmək",["maintain","manage","measure","mention"],0],
  ["v","əsaslandırmaq",["justify","judge","join","jump"],0],
  ["g","If I ___ more time, I would travel more.",["had","have","will have","would have"],0],
  ["g","The road ___ at the moment, so use the other one.",["is being repaired","is repairing","repairs","has repaired"],0],
  ["g","He told me that he ___ the film before.",["had seen","has seen","saw","was seeing"],0],
  ["g","I wish I ___ speak Chinese.",["could","can","will","would have"],0],
  ["g","By the time we arrived, the meeting ___.",["had started","started","has started","was starting"],0],
  ["g","She is the person ___ advice I trust most.",["whose","who","which","that"],0],
  ["g","You ___ have told me earlier; now it is too late.",["should","must","would","can"],0],
  ["g","___ working all night, he did not finish the report.",["Despite","Although","However","Because of"],0],
  ["g","The more you practise, ___ you become.",["the better","better","the best","more better"],0],
  ["g","I ___ to the gym three times a week these days.",["have been going","go to","am go","went"],0],
  ["g","It is high time we ___ a decision.",["made","make","will make","have made"],0],
  ["g","The letter ___ to have been written in 1920.",["is believed","believes","is believing","has believed"],0],
  ["g","Hardly ___ the door when the phone rang.",["had I opened","I had opened","did I open","I opened"],0],
  ["g","She suggested ___ the meeting until Monday.",["postponing","to postpone","postpone","postponed"],0],
  ["g","If he ___ harder last year, he would have passed.",["had studied","studied","has studied","would study"],0],
  ["r","What is the main topic of the text?",["The advantages and disadvantages of working from home","Why offices are closing","How to find a job online","The history of the laptop"],0],
  ["r","According to the text, why do many employees concentrate better at home?",["Nobody interrupts them often","The equipment is better","They work fewer hours","They have more meetings"],0],
  ["r","What problem do some workers report?",["They feel isolated","They earn less money","They cannot use computers","They must travel more"],0],
  ["r","Why is it harder to train new employees?",["They have never met their colleagues in person","They do not have laptops","They work at night","They live far away"],0],
  ["r","What do most experts believe about the future?",["A mixed model will be used","Everyone will work from home","Everyone will return to the office","Offices will disappear completely"],0],
  ["r","What does the last sentence suggest?",["The old five-day office week will not come back","Companies will close all offices","Workers will travel more","Nothing will change"],0],
  ["l","When will the new regulations start?",["At the beginning of next year","Immediately","At the end of this month","In two years"],0],
  ["l","What happened to demand?",["It stayed stable despite higher prices","It fell sharply","It disappeared","It doubled"],0],
  ["l","Why was the project delayed?",["Two team members resigned","The budget was cut","The client changed the plan","The office closed"],0],
  ["l","What does the research say?",["Students who sleep eight hours do better","Sleep has no effect","Students should study at night","Examinations are too difficult"],0],
  ["l","What is the company considering?",["Opening a second office","Closing the office","Reducing salaries","Moving abroad"],0]
 ]
},
4: { level:"B1+", after:25, part:2, pass:75, mins:50, title:"B1+ səviyyə imtahanı", ready:false,
 intro:"Pillə 2-nin ilk yarısı — 4500 sözə qədər. Oxu mətnləri uzanır, dinləmə sürətlənir.",
 plan:[["Söz","20 sual · 3000–4500 bandı, akademik sözlər"],["Qrammatika","15 sual · perfect zamanlar, passiv, şərt cümlələri 1-2"],["Oxu","8 sual · 350 sözlük mətn, True/False/Not Given"],["Dinləmə","7 sual · dialoq və monoloq, təbii sürət"]] },
5: { level:"B2", after:50, part:2, pass:75, mins:60, title:"B2 səviyyə imtahanı", ready:false,
 intro:"Pillə 2-nin sonu — 6000 söz. Oxuda B2 təsdiqi; danışıq və yazı Pillə 3-dən sonra yoxlanır.",
 plan:[["Söz","25 sual · 4500–6000 bandı, kollokasiyalar və frazeoloji fellər"],["Qrammatika","18 sual · şərt 3, mixed conditionals, inversiya, dolayı nitq"],["Oxu","10 sual · 500 sözlük akademik mətn, başlıq uyğunlaşdırma"],["Dinləmə","7 sual · mühazirə parçası, qeyd tamamlama"]] },
6: { level:"B2 (tam)", after:12, part:3, pass:75, mins:75, title:"B2 tam imtahanı", ready:false,
 intro:"Qrammatika pilləsinin sonu — dörd bacarığın hamısı. Bunu keçəndə B2 tam təsdiqlənir.",
 plan:[["Söz və qrammatika","30 sual · bütün 12 qrammatika mövzusu qarışıq"],["Oxu","12 sual · iki mətn, müqayisəli suallar"],["Dinləmə","10 sual · iki parça, çoxseçimli və cədvəl doldurma"],["Yazı","1 esse · 180 söz, avtomatik quruluş yoxlaması"],["Danışıq","3 mövzu · mikrofonla, tələffüz və axıcılıq faizi"]] },
7: { level:"IELTS", after:10, part:4, pass:70, mins:165, title:"IELTS tam sınaq imtahanı", ready:false,
 intro:"Real imtahan formatı və vaxtı. Sonda təxmini band bal (0–9) və hər bölmə üzrə ayrıca qiymət.",
 plan:[["Listening","40 sual · 30 dəq · 4 hissə, bir dəfə dinlənilir"],["Reading","40 sual · 60 dəq · 3 akademik mətn"],["Writing","2 tapşırıq · 60 dəq · Task 1 qrafik (150 söz), Task 2 esse (250 söz)"],["Speaking","3 hissə · 15 dəq · mikrofonla, cue card daxil"],["Nəticə","Hər bölmə üçün band bal və ümumi bal"]] }
};
