// Zirvə — qrammatika izahları, SADƏ format (Fuad: «rahat yolla, nümunələr altda ayrıca»).
// Hər qayda: h = başlıq, t = 1–2 sadə cümlə, tbl = kiçik cədvəl, ex = nümunələr [ingiliscə, azərbaycanca], no = səhv forma (xəbərdarlıq).
const GRAM_EXPL = {
g01: [
 {h:"1. İngilis cümləsində həmişə fel olur",
  t:"Azərbaycanca «yorğunam» deyirik, ayrıca söz lazım deyil. İngiliscə isə ayrıca söz lazımdır: am / is / are.",
  ex:[["I am tired.","Mən yorğunam."],["She is at home.","O evdədir."],["They are students.","Onlar tələbədir."]]},
 {h:"2. am / is / are — hansını seçim?",
  t:"Hansı sözü seçəcəyin «kim» haqqında danışdığından asılıdır. Özün haqqında — am. Bir nəfər və ya bir əşya haqqında (o, bu) — is. Bir neçə nəfər haqqında və «sən/siz» deyəndə — are.",
  tbl:[["I","am"],["he / she / it","is"],["we / you / they","are"]],
  ex:[["I am a manager.","Mən menecerəm."],["It is cold today.","Bu gün soyuqdur."],["We are ready.","Biz hazırıq."]]},
 {h:"3. Keçmişdə: was / were",
  t:"Keçmiş üçün («idim», «idi», «idik») am və is əvəzinə was, are əvəzinə were işlənir. Qayda eynidir, yalnız söz dəyişir.",
  tbl:[["I / he / she / it","was"],["we / you / they","were"]],
  ex:[["I was at work yesterday.","Dünən işdə idim."],["They were happy.","Onlar xoşbəxt idilər."]]},
 {h:"4. Yaşı da am / is / are ilə deyirik",
  t:"Azərbaycanca «yaşım var» deyirik, ona görə çoxları «have» işlədir. İngiliscə isə yaş «olmaq» kimi deyilir: «mən 25-əm». Ona görə am / is / are lazımdır.",
  ex:[["I am 25.","Mənim 25 yaşım var."],["My son is 6.","Oğlumun 6 yaşı var."]],
  no:"I have 25 — səhvdir"},
 {h:"5. Sual: am / is / are qabağa keçir",
  t:"Azərbaycanca sualı səs tonu ilə veririk. İngiliscə isə sözlərin yeri dəyişir: am / is / are cümlənin ən əvvəlinə keçir. Başqa heç nə əlavə etmirik.",
  ex:[["You are ready. → Are you ready?","Sən hazırsan. → Hazırsan?"],["She is a doctor. → Is she a doctor?","O həkimdir. → O həkimdir?"]]},
 {h:"6. İnkar: sonuna not əlavə et",
  t:"«Deyiləm, deyil» demək üçün am / is / are sözündən dərhal sonra not yazırıq. Danışıqda qısaldırıq: is not → isn't, are not → aren't (am not qısalmır).",
  ex:[["I am not tired.","Yorğun deyiləm."],["He isn't here.","O burada deyil."],["We aren't late.","Gecikməmişik."]]},
 {h:"7. have / has — «var» (məndə var)",
  t:"Bir şeyin səndə olduğunu demək üçün have işlənir: «mənim maşınım var» = «I have a car». O, bu (bir nəfər) haqqında danışanda have yox, has deyirik.",
  tbl:[["I / you / we / they","have"],["he / she / it","has"]],
  ex:[["I have a car.","Mənim maşınım var."],["She has two brothers.","Onun iki qardaşı var."],["We have a meeting at 3.","Saat 3-də görüşümüz var."]]},
 {h:"8. Sual və inkar: nə vaxt do / does / did lazımdır?",
  t:"Qayda belədir: cümlədə am / is / are (və ya was / were) varsa, do lazım DEYİL — onları sadəcə qabağa keçiririk. Cümlədə am / is / are YOXDURSA, sual və inkar üçün mütləq do / does / did lazımdır. Bu, bütün fellərə aiddir: work, go, eat, like, live, have, want — hamısına. Fellər qruplara bölünmür.",
  tbl:[["Cümlədə am / is / are var","do lazım deyil: Are you tired?"],["am / is / are yoxdur","do / does / did lazımdır: Do you work?"]],
  ex:[["You are tired. → Are you tired?","am/is/are var — do yoxdur"],["You work here. → Do you work here?","am/is/are yoxdur — do gəlir"],["She likes tea. → Does she like tea?","«o» olduğu üçün does"],["They went home. → Did they go home?","keçmiş olduğu üçün did"],["I don't eat meat.","Ət yemirəm."]],
  no:"Are you work here? / Do you tired? — səhvdir"},
 {h:"9. does / did gəlibsə, feldə -s və keçmiş forma itir",
  t:"does özü artıq «o» olduğunu, did isə keçmiş olduğunu göstərir. Ona görə əsas feldə -s və keçmiş forma ikinci dəfə yazılmır — fel sadə formada qalır.",
  ex:[["She works. → She doesn't work.","O işləyir. → O işləmir."],["He went. → Did he go?","O getdi. → O getdi?"]],
  no:"She doesn't works / Did he went — səhvdir"},
 {h:"10. Sual sözü ilə sual",
  t:"Harada, nə vaxt, niyə kimi suallarda sual sözü ən əvvələ gəlir. Ondan sonra do / does / did, sonra kim, ən axırda fel. Bu sıra həmişə eynidir.",
  ex:[["Where do you live?","Harada yaşayırsan?"],["What time does the shop open?","Mağaza saat neçədə açılır?"],["Why did they leave?","Onlar niyə getdi?"]]}
],
g02: [
 {h:"1. Fel «kim»-dən dərhal sonra gəlir",
  t:"Azərbaycanca fel sonda olur. İngiliscə sıra belədir: kim → nə edir → nəyi → harada → nə vaxt.",
  ex:[["I drink tea.","Mən çay içirəm."],["She reads books.","O kitab oxuyur."],["I met my teacher at the station yesterday.","Dünən stansiyada müəllimimi gördüm."]],
  no:"I tea drink — səhvdir"},
 {h:"2. Əvvəl yer, sonra vaxt",
  t:"Cümlədə həm «harada», həm «nə vaxt» varsa, adətən əvvəl yeri, sonra vaxtı yazırıq. İkisi də cümlənin sonunda olur.",
  ex:[["She works in Baku every day.","O hər gün Bakıda işləyir."],["We were at home all day.","Bütün günü evdə idik."]]},
 {h:"3. Vaxt sözü əvvələ də keçə bilər",
  t:"«Dünən», «bu gün» kimi sözləri vurğulamaq istəsən, cümlənin ən əvvəlinə qoya bilərsən. Amma «kim» ilə fel arasına qoymaq olmaz.",
  ex:[["Yesterday I met my teacher.","Dünən müəllimimi gördüm."]],
  no:"I yesterday met — səhvdir (vaxt «kim» ilə fel arasına girmir)"},
 {h:"4. always, usually, often, sometimes, never — feldən əvvəl",
  t:"«Həmişə, adətən, tez-tez, bəzən, heç vaxt» sözləri nə qədər tez-tez etdiyini göstərir. Onlar işi bildirən feldən dərhal əvvəl gəlir.",
  ex:[["I usually walk to work.","Adətən işə piyada gedirəm."],["I never drink coffee.","Heç vaxt qəhvə içmirəm."],["We often watch films.","Tez-tez film izləyirik."]],
  no:"I go always — səhvdir"},
 {h:"5. Amma am / is / are-dən sonra",
  t:"Cümlədə iş görən fel yox, am / is / are varsa, bu sözlər onlardan SONRA gəlir. Bunu yadda saxlamaq üçün: am/is/are + always.",
  ex:[["She is always late.","O həmişə gecikir."],["I am never tired in the morning.","Səhər heç vaxt yorğun olmuram."]]},
 {h:"6. every day, twice a week — cümlənin sonunda",
  t:"Bir neçə sözdən ibarət vaxt ifadələri (hər gün, həftədə iki dəfə, ayda bir dəfə) feldən əvvələ yox, cümlənin sonuna gəlir.",
  ex:[["I go to the gym twice a week.","Həftədə iki dəfə idman zalına gedirəm."],["He calls his mother every day.","Hər gün anasına zəng edir."]]},
 {h:"7. Sualda do / does qabağa keçir",
  t:"Adi fellərdə sual verəndə do və ya does «kim»-dən əvvələ gəlir. Sual sözü (where, what) varsa, o, do-dan da əvvəldə durur.",
  ex:[["Do you like music?","Musiqini sevirsən?"],["Where do you work?","Harada işləyirsən?"]],
  no:"Where you work? — səhvdir"},
 {h:"8. give me the book — iki obyekt",
  t:"«Vermək, göndərmək, göstərmək» kimi fellərdə iki şey olur: kimə və nəyi. İki yol var: «kimə + nəyi» və ya «nəyi + to + kimə». Hər ikisi düzdür.",
  ex:[["Give me the book.","Kitabı mənə ver."],["Give the book to me.","Kitabı mənə ver."]],
  no:"Give to me the book — səhvdir"},
 {h:"9. Sifət ismdən əvvəl gəlir və cəm olmur",
  t:"«Yeni, böyük, gözəl» kimi sözlər əşyanın adından əvvəl gəlir — azərbaycancadakı kimi. Əşya çox olanda belə bu sözə -s artırılmır.",
  ex:[["a new car","yeni maşın"],["two new cars","iki yeni maşın"]],
  no:"two news cars — səhvdir"}
]
};
GRAM.forEach(g=>{if(GRAM_EXPL[g.id])g.expl=GRAM_EXPL[g.id];});
