// Danışıq sessiyaları — hər 5 dərsdən bir. Cümlələr həmin dərslərin sözlərindən qurulub.
// Sessiya 20 dəqiqədir; cümlələr dövr edir. Mac nitq tanıması ilə müqayisə olunur.
const SPEAK = {
1: { lessons:[1,5], items:[
 "I have a lot of work this week.",
 "What do you want to do today?",
 "She is at home with her family.",
 "We can meet at the same place.",
 "I think this is a very good book.",
 "He does not know where they are.",
 "Can you help me with this problem?",
 "It is late, but I still want to talk.",
 "My school is not far from my house.",
 "Do you like to play after work?",
 "Tell me about your country.",
 "I will call you at the end of the day.",
 "Let me see what you have.",
 "Every day I find something new.",
 "The old man lives in a small house.",
 "Why do you ask so many questions?",
 "Keep this between you and me.",
 "I need to start early and study all day.",
 "Which way should we go from here?",
 "Life is not a game, but it is good.",
 "Give me one more week, and I will show you.",
 "They say that family is important.",
 "We are a small group, but we are good.",
 "I want to see the world one day."
]},
2: { lessons:[6,10], items:[
 "My friend has a new job in the city.",
 "I read a book every night in my room.",
 "How much does this cost?",
 "I hope you understand my idea.",
 "We spend a lot of money on food.",
 "Thank you for your help today.",
 "The student asked a hard question.",
 "Can you send me the information today?",
 "I believe we can win this game.",
 "She speaks two languages very well.",
 "It happened a long time ago.",
 "Let us walk to the center of the town.",
 "My mother lives far from here.",
 "I will pay for the water and the food.",
 "Do you remember the name of that place?",
 "We have a plan for the next month.",
 "The car is old, but it still runs.",
 "I want to learn English at a high level.",
 "Open the door and let the light in.",
 "What is the answer to this question?",
 "He decided to stay at home today.",
 "This is a real problem, and we need a real answer.",
 "Music helps me think.",
 "In half an hour we will be free."
]},
3: { lessons:[11,15], items:[
 "Please wait a minute; I am almost done.",
 "It is easy to say, but hard to do.",
 "I usually eat at home in the morning.",
 "My father works in a big shop near the road.",
 "Can you explain the difference between these two words?",
 "We agree on the main points of the plan.",
 "She is a strong girl with a clear mind.",
 "Let us practice every morning for half an hour.",
 "The teacher asked us to draw a picture.",
 "I enjoy my work, especially in the morning.",
 "Technology changes our culture every day.",
 "Turn right at the street and walk forward.",
 "He finally accepted the decision.",
 "We have a chance to improve our performance.",
 "Check the date and sign the paper.",
 "The news today is not good.",
 "My phone is on the table near the door.",
 "I want to travel and see the world.",
 "Health is more important than money.",
 "Listen first, and then answer.",
 "There is no reason to fight.",
 "The current situation is difficult, but we will pass it.",
 "Choose one, and stay with your choice.",
 "Everything is possible if you try."
]},
4: { lessons:[16,20], items:[
 "Do not worry, I will not forget what you said.",
 "In my opinion, the park is most beautiful in summer.",
 "Could you tell me exactly where the bus station is?",
 "I am sorry, but the manager is not ready yet.",
 "Let me guess: you missed the bus again this morning.",
 "We are going on a trip to the village tomorrow.",
 "I wonder if the hotel has a free room this evening.",
 "It depends on the season and on how you feel.",
 "Anyway, the final decision is yours, not mine.",
 "My son wants to become a doctor when he grows up.",
 "The key to success is simple: never stop trying.",
 "Would you like something hot or cold to drink?",
 "Can I leave a message for your brother, please?",
 "I have no doubt that you will pass the interview.",
 "Let us sit by the window and watch the stars.",
 "She promised to call me yesterday, but she forgot.",
 "This is a huge challenge, but it is worth it.",
 "I need to get some sleep before the long trip.",
 "Keep your eyes on the goal and avoid trouble.",
 "He is a serious player, but he has a good heart.",
 "Have you noticed how quickly the children are growing?",
 "Every evening we sit in the park and talk about life.",
 "Stay positive; one bad day does not make a bad life.",
 "Take a seat, the doctor will see you in a minute."
]},
5: { lessons:[21,25], items:[
 "What do you usually prefer to do on the weekend?",
 "I usually exercise in the afternoon, before it gets dark.",
 "Can you recommend a cheap but good restaurant near here?",
 "Yeah, that sounds like fun, but my budget is small this month.",
 "Could you ask the taxi driver to go straight ahead, please?",
 "My sister has always dreamed of studying at a famous university.",
 "Nobody is perfect, so do not worry about small mistakes.",
 "Let me give you some advice: never trust a deal that is too cheap.",
 "The weather is wonderful today; shall we walk along the river?",
 "I will reply to your email as soon as I can.",
 "Okay, I completely agree with you, but somebody still has to pay.",
 "She smiled and said, \"Welcome to our home, please come in.\"",
 "He earns a good income, but he never has time for dinner.",
 "I have a wonderful memory of that song from when I was young.",
 "Is it safe to leave my bag here while I go to the library?",
 "Take it easy; too much stress is bad for your health.",
 "My favorite part of the day is cooking dinner with my partner.",
 "Imagine how excited the kids will be when they see the sea.",
 "We made slow progress at first, but now things are going well.",
 "Let us meet at the corner in front of the library in an hour.",
 "To tell you the truth, I did not discover this place myself.",
 "The expert says that daily exercise helps to protect us from disease.",
 "It is not fair to expect him to fix everything alone.",
 "Be quick, or the crowd will take all the good seats."
]},
6: { lessons:[26,30], items:[
 "Unfortunately, our flight has been delayed because of the heavy rain.",
 "I really appreciate your help; I could hardly do it alone.",
 "Could you remind me what time the concert starts tonight?",
 "The tickets were extremely expensive, but the show was totally worth it.",
 "I am afraid I cannot afford a holiday on an island this year.",
 "Let us take the path along the beach; it is more quiet there.",
 "My neighbor is a nurse, so she works strange hours at the hospital.",
 "Would you like a cup of coffee, or do you prefer something cold?",
 "It is impossible to relax when the traffic outside makes so much noise.",
 "She hates to complain, but the room was not very comfortable.",
 "Do not ignore the pain; you should see a doctor as soon as possible.",
 "The owner of the museum showed us a secret room under the floor.",
 "I am glad you finally escaped the busy city for a weekend.",
 "Always wash your hands carefully before lunch; it keeps you healthy.",
 "That sounds familiar; I think we have met somewhere before.",
 "Apparently the temperature will drop tonight, so wear something warm.",
 "As my coach likes to say, practice is essential if you want strength.",
 "I would like to make a suggestion, if you have a minute.",
 "We had to repeat the experiment twice, but the second time it worked.",
 "Please keep the gift a secret; it is a surprise for my sister.",
 "The guide told us that the island is dangerous for tourists after dark.",
 "I am extremely busy all day, so let us meet tomorrow instead.",
 "He refused to shake my hand, which was a little strange.",
 "It is a tough decision, but in the end it is your call."
]},
7: { lessons:[31,35], items:[
 "I definitely need a cup of tea before I can concentrate on anything.",
 "The rent is reasonable, but the flat is tiny and the walls are thin.",
 "Hi, I have an appointment with the professor this morning, but I am running late.",
 "Could you give me a few tips on how to make a good first impression?",
 "Do not blame yourself; it was a simple mistake, and anyone could have made it.",
 "I did not necessarily agree with him, but I respect his judgment.",
 "My dad is going to retire next year, and he plans to travel along the coast.",
 "She has a real talent for languages; she picks up new phrases in no time.",
 "Sorry to bother you, but is this seat free, or is somebody sitting here?",
 "We should celebrate; after months of hard work, the outcome was better than we expected.",
 "I always practice at home before a formal presentation, just to feel ready.",
 "It is a lovely neighborhood, but the passengers on the morning bus are always in a rush.",
 "My priority right now is to find a stable job with a good salary.",
 "Hold on a second; I need to lock the door and turn off the lights.",
 "He insists that breakfast is the most important meal of the day.",
 "I was unable to sleep last night because somebody kept shouting in the yard.",
 "Take a deep breath and slowly count in your head; it really helps.",
 "I am not angry, just a little sad that you did not tell me the truth.",
 "Can I pay online, or do I have to come to the office in person?",
 "The old farmer has a vast knowledge of the plants that grow wild on the hill.",
 "The instructions were so bad that I gave up in the middle.",
 "It is a rare chance, so I strongly advise you not to reject the offer.",
 "Meanwhile, the kids went out to play, and the house was finally quiet.",
 "Old habits die hard, but with a little discipline you can change almost anything."
]},
8: { lessons:[36,40], items:[
 "Excuse me, is there a place nearby where I can repair my bike?",
 "I owe you one; I honestly could not have done it without your help.",
 "I am really grateful for the invitation, but I am afraid I cannot make it.",
 "Whenever I feel nervous, I stop, breathe deeply and remind myself why I started.",
 "Personally, I think the movie was brilliant, although the plot was a bit confusing.",
 "Can I borrow your coat? I did not expect it to be this cold today.",
 "Please do not be upset; it was partly my fault, and I am really sorry.",
 "Things are moving at a slow pace, but we are making steady progress every day.",
 "The elderly man next door rarely leaves his apartment when it snows outside.",
 "Better luck next time; you did your best, and that is what really counts.",
 "I bet you have never seen anything as beautiful as this landscape in spring.",
 "The storm was a disaster for the farmers who lost most of their crops.",
 "I am in a bad mood today, so please do not take it personally.",
 "It is unlikely that we will find accommodation in the city center this late.",
 "We were lucky to find a small place with brilliant music and wonderful cake.",
 "Could you help me install this program? I keep getting an error message.",
 "The singer's new album is extraordinary, and I have been listening to it constantly.",
 "I am proud of you; you coped with a very difficult situation perfectly.",
 "We need to update the plan and calculate how much the repairs will cost.",
 "The kids stared at the huge truck in silence, then everybody began to laugh.",
 "My mom always says that being honest is the best policy, and she is right.",
 "If you have a spare minute, could you persuade him to join us for dinner?",
 "Pollution in urban areas is gradually getting worse, especially in the hot summer months.",
 "Do not be scared of making mistakes; every hero started as an ordinary person."
]},
9: { lessons:[41,45], items:[
 "Nowadays teenagers spend so much time online that they rarely go outside to play.",
 "I must apologize for the mess; I did not expect any guests this afternoon.",
 "Would you mind if we cancelled the meeting? Something important has come up at home.",
 "According to the weather forecast, there might be a flood in the valley this weekend.",
 "I really admire your confidence; you speak in public as if it were nothing.",
 "Could you lend me your pen for a minute? Mine has just run out.",
 "Do not be embarrassed; everybody forgets their lines at least once in their life.",
 "She has a real passion for music and dreams of becoming a famous musician.",
 "I regret not studying harder for the exam, but it is too late to worry now.",
 "We are keen to hear your opinion, so please do not keep silent at the meeting.",
 "Let me briefly repeat the main points: we need a reliable plan, a clear budget and a lot of time.",
 "Just between you and me, I found the lecture extremely boring and far too long.",
 "My cousin lives overseas, so we mostly chat online and meet only once a year.",
 "Could I have the menu, please? I would like to try something with cheese.",
 "He pretended not to notice, but I could see the pride in his eyes.",
 "It was literally the best celebration of my life; I will remember it forever.",
 "Taking a hot shower after a long day at work is pure joy for me.",
 "I do not dare to swim here; the water is deep and the waves are rough.",
 "The old man whispered a tale about the moon and a magic wooden box.",
 "Try to adapt to the new situation instead of resisting every single change.",
 "A good sense of humor helps you overcome almost any difficulty in life.",
 "Just out of interest, why did you decide to specialize in music therapy?",
 "I occasionally play the guitar, but my sister is the real champion of the piano.",
 "If you ask me, the best way to motivate students is to let them be creative."
]},
10: { lessons:[46,50], items:[
 "Hello, I am sorry to interrupt, but could you tell me where the exit is?",
 "My grandmother always says that happiness is found in small things, like a warm cup of tea.",
 "Hopefully the weather will stay dry, because we are planning to put up a tent on the shore.",
 "I barely understood a word at first, but gradually my vocabulary grew and my accent improved.",
 "Do not hesitate to ask for feedback; it is the fastest way to improve your skills.",
 "Wherever you go in the world, a genuine smile is understood without any words at all.",
 "I reckon the probability of rain is quite high, so take a coat just in case.",
 "Honestly, I was so ashamed of my silly mistake that I could not look at anyone.",
 "She wiped her eyes, smiled gently and said that everything would be alright in the end.",
 "If you have a sensible plan and a bit of determination, nothing is really impossible.",
 "The first paragraph is clear, but the logic of the second one is a little weird.",
 "We were fortunate to get a bargain on the tickets, so the whole trip cost almost nothing.",
 "My uncle is an immigrant who came here with nothing and built an incredible life for his family.",
 "Stop wandering around the house and help me find the envelope with the stamps, please.",
 "Firstly, thank you all for coming, and please switch off your phones before the lecture begins.",
 "Life is not a race; learn to enjoy the journey and not only the destination.",
 "It was a painful lesson, but it taught me to think differently about money and success.",
 "I kept a diary during my adventure, and now I love to read it on quiet autumn evenings.",
 "Can you give me a hint? This puzzle is driving me crazy, and I am about to give up.",
 "The mayor promised to publish the real numbers shortly, but honestly, nobody believes him anymore.",
 "Physically I was exhausted after the tournament, but mentally I felt stronger than ever before.",
 "It is commonly believed that learning a language takes years, but a daily routine can make a tremendous difference.",
 "Take your time and summarize the main points correctly; there is no need to panic.",
 "Looking back on a lifetime of learning, I would not change a single step of the journey."
]}
};
