// Danışıq sessiyaları — hər 5 dərsdən bir. Cümlələr həmin dərslərin sözlərindən qurulub.
// Sessiya 20 dəqiqədir; cümlələr dövr edir. Mac nitq tanıması ilə müqayisə olunur.
const SPEAK = {
1: { lessons:[1,5], items:[
 "I have a lot of work this week.",
 "What do you want to do today?",
 "She is at home with her family.",
 "We can meet at the same place.",
 "I think this is a very good book.",
 "He does not know where they are.",
 "Can you help me with this problem?",
 "It is late, but I still want to talk.",
 "My school is not far from my house.",
 "Do you like to play after work?",
 "Tell me about your country.",
 "I will call you at the end of the day.",
 "Let me see what you have.",
 "Every day I find something new.",
 "The old man lives in a small house.",
 "Why do you ask so many questions?",
 "Keep this between you and me.",
 "I need to start early and study all day.",
 "Which way should we go from here?",
 "Life is not a game, but it is good.",
 "Give me one more week, and I will show you.",
 "They say that family is important.",
 "We are a small group, but we are good.",
 "I want to see the world one day."
]},
2: { lessons:[6,10], items:[
 "My friend has a new job in the city.",
 "I read a book every night in my room.",
 "How much does this cost?",
 "I hope you understand my idea.",
 "We spend a lot of money on food.",
 "Thank you for your help today.",
 "The student asked a hard question.",
 "Can you send me the information today?",
 "I believe we can win this game.",
 "She speaks two languages very well.",
 "It happened a long time ago.",
 "Let us walk to the center of the town.",
 "My mother lives far from here.",
 "I will pay for the water and the food.",
 "Do you remember the name of that place?",
 "We have a plan for the next month.",
 "The car is old, but it still runs.",
 "I want to learn English at a high level.",
 "Open the door and let the light in.",
 "What is the answer to this question?",
 "He decided to stay at home today.",
 "This is a real problem, and we need a real answer.",
 "Music helps me think.",
 "In half an hour we will be free."
]},
3: { lessons:[11,15], items:[
 "Please wait a minute; I am almost done.",
 "It is easy to say, but hard to do.",
 "I usually eat at home in the morning.",
 "My father works in a big shop near the road.",
 "Can you explain the difference between these two words?",
 "We agree on the main points of the plan.",
 "She is a strong girl with a clear mind.",
 "Let us practice every morning for half an hour.",
 "The teacher asked us to draw a picture.",
 "I enjoy my work, especially in the morning.",
 "Technology changes our culture every day.",
 "Turn right at the street and walk forward.",
 "He finally accepted the decision.",
 "We have a chance to improve our performance.",
 "Check the date and sign the paper.",
 "The news today is not good.",
 "My phone is on the table near the door.",
 "I want to travel and see the world.",
 "Health is more important than money.",
 "Listen first, and then answer.",
 "There is no reason to fight.",
 "The current situation is difficult, but we will pass it.",
 "Choose one, and stay with your choice.",
 "Everything is possible if you try."
]}
};
