// Zirvə — Writing və Speaking tapşırıqları (orijinal, Zirvə üçün yazılıb).
// Format qaydaları ielts.org-dan yoxlanılıb (2026-10-06): Writing 60 dəq; Task 1 ≥150 söz (~20 dəq), Task 2 ≥250 söz (~40 dəq), Task 2-nin çəkisi böyükdür.
// Speaking 11–14 dəq; Part 2: 1 dəq hazırlıq, 2 dəqiqəyə qədər danışıq (ielts.org, ielts.idp.com).
const WRITE_CRIT = {
  a: [ // A2/B1 qısa yazılar üçün sadə meyarlar
    ["Tapşırıq","Sualdakı bütün hissələrə cavab verdimmi?"],
    ["Ardıcıllıq","Cümlələr məntiqli sıradadır, and/but/because/so ilə bağlanıb?"],
    ["Söz","Mövzuya uyğun sözlər işlətdim, eyni sözü çox təkrarlamadım?"],
    ["Qrammatika","Fel zamanları, -s, artikllar düzdür? Hər cümlədə fel var?"]
  ],
  t1: [
    ["Task Achievement","Overview (əsas tendensiya) yazdım? Əsas xüsusiyyətləri seçib rəqəmlərlə müqayisə etdim? Şəxsi fikir yazmadım?"],
    ["Coherence and Cohesion","Məlumat məntiqli qruplaşdırılıb, abzaslar var, bağlayıcılar təbii işlənib?"],
    ["Lexical Resource","Artım/azalma sözləri müxtəlifdir (rise, decline, remain stable), rəqəmlər düz ifadə olunub?"],
    ["Grammatical Range and Accuracy","Müxtəlif cümlə quruluşu, düz zaman, müqayisə formaları?"]
  ],
  t2: [
    ["Task Response","Sualın HƏR hissəsinə cavab verdim? Mövqe (sual tələb edirsə) aydındır və əsaslandırılıb?"],
    ["Coherence and Cohesion","Giriş, 2–3 əsas abzas, nəticə; hər abzasın bir əsas fikri var?"],
    ["Lexical Resource","Mövzu sözləri dəqiqdir, paraphrase etdim, kollokasiyalar düzdür?"],
    ["Grammatical Range and Accuracy","Mürəkkəb cümlələr (although, which, if) var və səhvsizdir?"]
  ]
};
const WRITING = [
// --- A2: düzgün cümlə, qısa mesaj, təsvir, gündəlik hadisə (60–100 söz) ---
{ id:"w01", level:"A2", kind:"Mesaj", mins:15, min:50, max:80, crit:"a",
  title:"Dosta dəvət mesajı",
  prompt:"Write a message to an English-speaking friend. Invite them to your city for a weekend. Say: when they should come, what you will do together, and what they should bring.",
  az:"İngilisdilli dostunu həftəsonu şəhərinə dəvət et. Üç hissəni yaz: nə vaxt, birlikdə nə edəcəksiniz, nə gətirsin.",
  model:"Hi Sam,\n\nWould you like to visit me in Baku next weekend? You can come on Friday evening and stay until Sunday. On Saturday we can walk around the Old City and have lunch by the sea. In the evening I want to show you the Flame Towers. Please bring comfortable shoes, because we will walk a lot, and a warm jacket — it is windy here in October.\n\nLet me know!\nFuad" },
{ id:"w02", level:"A2", kind:"Təsvir", mins:15, min:60, max:90, crit:"a",
  title:"Ailə üzvünün təsviri",
  prompt:"Describe a person in your family. Write about their appearance, their job or daily life, and why you like spending time with them.",
  az:"Ailəndən birini təsvir et: görünüşü, işi/gündəlik həyatı və onunla vaxt keçirməyi niyə sevirsən.",
  model:"My older brother is called Kamran. He is thirty years old and he is tall and thin, with short dark hair. He works as an engineer at a construction company, so he usually gets up very early. In the evenings he often plays football with his friends. I like spending time with him because he is funny and he always gives me good advice. Last summer we travelled to Gabala together, and it was one of my best holidays." },
{ id:"w03", level:"A2", kind:"Hadisə", mins:20, min:70, max:100, crit:"a",
  title:"Dünən nə oldu?",
  prompt:"Write about something interesting or unusual that happened to you recently. Say where you were, what happened, and how you felt.",
  az:"Son vaxtlar başına gələn maraqlı və ya qeyri-adi bir hadisəni yaz: harada idin, nə baş verdi, necə hiss etdin. Past Simple və Past Continuous işlət.",
  model:"Last Tuesday I was waiting for the bus after work when an old man asked me for directions. He was looking for a hospital, but he didn't have a phone. The hospital was not far, so I decided to walk there with him. On the way he told me that he was a teacher for forty years. When we arrived, he thanked me and gave me a small bag of sweets. I missed my bus, but I felt really happy that evening." },
{ id:"w04", level:"A2", kind:"Mesaj", mins:15, min:50, max:80, crit:"a",
  title:"Müdirə üzr məktubu",
  prompt:"You cannot come to work tomorrow. Write an email to your manager. Explain why, say what you will do about your work, and suggest when you can come back.",
  az:"Sabah işə gələ bilmirsən. Müdirə e-poçt yaz: səbəb, işini necə həll edəcəksən, nə vaxt qayıdacaqsan. Rəsmi, nəzakətli ton.",
  model:"Dear Mr Aliyev,\n\nI am sorry, but I cannot come to the office tomorrow because I have a doctor's appointment in the morning. I will finish the monthly report tonight and send it to you before 9 am. If there are any urgent questions, I will answer my phone and emails in the afternoon. I will be back at work on Thursday.\n\nThank you for your understanding.\nBest regards,\nFuad" },
{ id:"w05", level:"A2", kind:"Təsvir", mins:20, min:70, max:100, crit:"a",
  title:"Sevdiyin yer",
  prompt:"Describe a place you like to visit in your free time. What does it look like? What do you do there? Why is it special for you?",
  az:"Boş vaxtında getməyi sevdiyin yeri təsvir et: necə görünür, orada nə edirsən, niyə xüsusidir.",
  model:"" },
{ id:"w06", level:"A2", kind:"Plan", mins:20, min:70, max:100, crit:"a",
  title:"Gələn ay üçün planlar",
  prompt:"Write about your plans for next month. Include work, study and free time. Explain why each plan is important to you.",
  az:"Gələn ay üçün planlarını yaz: iş, təhsil, boş vaxt. Hər planın niyə vacib olduğunu de. going to və will işlət.",
  model:"" },
// --- B1: abzas, fikir və səbəb, müqayisə (100–180 söz) ---
{ id:"w07", level:"B1", kind:"Fikir abzası", mins:25, min:100, max:150, crit:"a",
  title:"Onlayn öyrənmə",
  prompt:"Some people prefer to learn online, while others prefer classes with a teacher. Which do you prefer? Write one paragraph with your opinion, two reasons and an example.",
  az:"Onlayn öyrənmə, yoxsa müəllimlə dərs? Bir abzas: fikrin, iki səbəb, bir nümunə. Topic sentence ilə başla.",
  model:"" },
{ id:"w08", level:"B1", kind:"Müqayisə", mins:25, min:120, max:160, crit:"a",
  title:"Şəhər və kənd",
  prompt:"Compare living in a city with living in the countryside. Write about two advantages of each and say where you would prefer to live in the future.",
  az:"Şəhər və kənd həyatını müqayisə et: hər birinin iki üstünlüyü və gələcəkdə harada yaşamaq istədiyin. whereas, while, on the other hand işlət.",
  model:"" },
{ id:"w09", level:"B1", kind:"Problem və həll", mins:30, min:130, max:180, crit:"a",
  title:"Tıxac problemi",
  prompt:"Traffic is a serious problem in many big cities. Describe the main causes of the problem and suggest two practical solutions.",
  az:"Böyük şəhərlərdə tıxac: əsas səbəbləri yaz və iki praktik həll təklif et.",
  model:"" },
// --- IELTS Task 1 (Academic): vizualın təsviri, ≥150 söz, ~20 dəq ---
{ id:"w10", level:"B2", kind:"IELTS Task 1 · bar chart", mins:20, min:150, crit:"t1", ielts:1,
  title:"Gənclərin boş vaxtı",
  prompt:"The chart below shows the average number of hours per week that young people (16–24) in one country spent on four leisure activities in 2015 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  az:"Diaqramı təsvir et: overview (ən böyük dəyişiklik), sonra rəqəmlərlə müqayisə. Şəxsi fikir yazma.",
  chart:{type:"bar",unit:"hours per week",cats:["Social media","Sport","Reading","Video games"],series:[["2015",[8,6,4,5]],["2025",[15,4,2,7]]]} },
{ id:"w11", level:"B2", kind:"IELTS Task 1 · line graph", mins:20, min:150, crit:"t1", ielts:1,
  title:"İctimai nəqliyyat sərnişinləri",
  prompt:"The graph below shows the number of passengers (in millions) using three types of public transport in a city between 2000 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  az:"Xətti qrafik: hər nəqliyyat növünün tendensiyasını (artım, azalma, sabitlik) və müqayisəni yaz.",
  chart:{type:"line",unit:"million passengers",cats:["2000","2005","2010","2015","2020","2025"],series:[["Metro",[120,135,160,190,150,210]],["Bus",[200,190,175,160,120,130]],["Tram",[40,42,45,44,30,35]]]} },
{ id:"w12", level:"B2", kind:"IELTS Task 1 · table", mins:20, min:150, crit:"t1", ielts:1,
  title:"Ev təsərrüfatının xərcləri",
  prompt:"The table below shows the percentage of household spending on five categories in three countries in 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  az:"Cədvəl: ən böyük və ən kiçik xərcləri, ölkələr arasındakı əsas fərqləri seç. Bütün rəqəmləri sadalama.",
  chart:{type:"table",unit:"% of household spending",cats:["Housing","Food","Transport","Education","Leisure"],series:[["Country A",[35,15,12,8,10]],["Country B",[25,28,10,5,7]],["Country C",[30,20,15,12,13]]]} },
{ id:"w13", level:"B2", kind:"IELTS Task 1 · pie charts", mins:20, min:150, crit:"t1", ielts:1,
  title:"Elektrik mənbələri",
  prompt:"The pie charts below show the sources of electricity in one country in 2005 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  az:"İki dairəvi diaqram: hansı mənbə artıb, hansı azalıb, ən böyük pay hansıdır.",
  chart:{type:"pie",unit:"%",cats:["Gas","Oil","Hydro","Wind","Solar"],series:[["2005",[55,25,15,4,1]],["2025",[48,8,14,18,12]]]} },
// --- IELTS Task 2: ≥250 söz, ~40 dəq ---
{ id:"w14", level:"B1", kind:"IELTS Task 2 · opinion (hazırlıq)", mins:40, min:250, crit:"t2", ielts:2,
  title:"Uşaqlar və smartfon",
  prompt:"Some people think that children under twelve should not have their own smartphone.\n\nTo what extent do you agree or disagree?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience.",
  az:"Fikir esse. Mövqeyini girişdə aydın yaz, iki əsas abzasda əsaslandır, nəticədə təkrarla. Hazırlıq mərhələsi: əvvəlcə 150 sözlə başla, sonra 250-yə çat.",
  plan:["Giriş: mövzunu öz sözlərinlə de + mövqeyin (məs. mostly agree).","Abzas 1: əsas səbəb + izah + nümunə.","Abzas 2: ikinci səbəb və ya qarşı fikir + niyə razı deyilsən.","Nəticə: mövqeyi təkrar et, yeni fikir əlavə etmə."] },
{ id:"w15", level:"B2", kind:"IELTS Task 2 · discussion", mins:40, min:250, crit:"t2", ielts:2,
  title:"Universitet: iş üçün, yoxsa bilik üçün",
  prompt:"Some people believe that the main purpose of university is to prepare students for employment. Others think universities should provide knowledge for its own sake.\n\nDiscuss both these views and give your own opinion.",
  az:"Hər İKİ fikri müzakirə et və öz fikrini də yaz — üç hissə tələb olunur.",
  plan:["Giriş: iki fikri paraphrase et + öz mövqeyin qısaca.","Abzas 1: birinci fikir — səbəblər, nümunə.","Abzas 2: ikinci fikir — səbəblər, nümunə.","Nəticə: öz fikrin (və ya abzas 2-nin sonunda)."] },
{ id:"w16", level:"B2", kind:"IELTS Task 2 · advantages/disadvantages", mins:40, min:250, crit:"t2", ielts:2,
  title:"Uzaqdan iş",
  prompt:"More and more people are working from home instead of in an office.\n\nDo the advantages of this trend outweigh the disadvantages?",
  az:"Sual «outweigh» soruşur — sadəcə sadalama yox, hansının ağır gəldiyini aydın de.",
  plan:["Giriş: tendensiya + cavabın (məs. advantages outweigh).","Abzas 1: çatışmazlıqlar (qısa, ədalətli).","Abzas 2: üstünlüklər (daha güclü, nümunə ilə).","Nəticə: niyə üstünlüklər ağır gəlir."] },
{ id:"w17", level:"B2", kind:"IELTS Task 2 · problem/solution", mins:40, min:250, crit:"t2", ielts:2,
  title:"Gənclər arasında hərəkətsizlik",
  prompt:"Many young people today do not get enough physical exercise.\n\nWhat are the causes of this problem, and what measures could be taken to solve it?",
  az:"İki hissə: səbəblər VƏ həllər. Hər həll bir səbəbə cavab versə, esse güclü olur.",
  plan:["Giriş: problem + iki hissəli cavab planı.","Abzas 1: 2 səbəb (izah + nümunə).","Abzas 2: 2 həll (kim etməlidir, necə).","Nəticə: qısa xülasə."] },
{ id:"w18", level:"B2", kind:"IELTS Task 2 · two-part question", mins:40, min:250, crit:"t2", ielts:2,
  title:"Turizm və yerli mədəniyyət",
  prompt:"International tourism has grown rapidly in recent decades.\n\nWhy do so many people travel abroad today? Is this a positive or negative development for local communities?",
  az:"İki ayrı sual var — hər birinə ayrıca abzas ayır.",
  plan:["Giriş: mövzu + iki suala qısa cavab.","Abzas 1: niyə çox insan səyahət edir (2 səbəb).","Abzas 2: yerli icmalar üçün müsbət/mənfi + öz qiymətləndirmən.","Nəticə."] }
];

const SPEAKING = [
// A2: funksional danışıq — şəxsi məlumat, keçmiş hadisə, plan, seçim, müqayisə, problem
{ id:"s01", level:"A2", part:"Gündəlik", prep:15, secs:60, title:"Özün haqqında",
  q:["Tell me about yourself: where you live, what you do, and what you like doing in your free time."],
  help:["I live in … with …","I work as … / I'm studying …","In my free time I usually …","I really enjoy … because …"] },
{ id:"s02", level:"A2", part:"Keçmiş hadisə", prep:20, secs:90, title:"Son həftəsonu",
  q:["What did you do last weekend? Describe it from beginning to end and say how you felt."],
  help:["On Saturday morning I …","After that, …","In the evening we …","It was … because …"] },
{ id:"s03", level:"A2", part:"Plan", prep:20, secs:90, title:"Gələcək planlar",
  q:["What are you going to do next summer? Why?"],
  help:["I'm going to …","I'd like to … because …","If I have time, I'll …"] },
{ id:"s04", level:"A2", part:"Seçim və səbəb", prep:20, secs:60, title:"Çay, yoxsa qəhvə?",
  q:["Which do you prefer: tea or coffee? Morning or evening? Give a reason for each choice."],
  help:["I prefer … to … because …","For me, … is better, since …"] },
{ id:"s05", level:"A2", part:"Müqayisə", prep:30, secs:90, title:"İki telefon",
  q:["Compare your current phone with your previous phone. Which is better and why?"],
  help:["My new phone is … than my old one.","It isn't as … as …","The best thing about it is …"] },
{ id:"s06", level:"B1", part:"Problem və həll", prep:30, secs:90, title:"Səs-küylü qonşu",
  q:["Your neighbour plays loud music late at night. What would you do? Explain step by step."],
  help:["First, I would …","If that didn't work, I'd …","The problem is that …"] },
// IELTS Part 1 (4–5 dəq, tanış mövzular)
{ id:"s07", level:"B1", part:"IELTS Part 1", prep:0, secs:30, ielts:1, title:"Hometown",
  q:["Where is your hometown?","What do you like most about it?","Is it a good place for young people? Why?","Has it changed much in recent years?"],
  help:["Hər suala 2–3 cümlə: cavab + səbəb + kiçik nümunə."] },
{ id:"s08", level:"B1", part:"IELTS Part 1", prep:0, secs:30, ielts:1, title:"Work or study",
  q:["Do you work or are you a student?","What do you enjoy about your job?","Is there anything you would like to change about it?","Would you like to study abroad in the future?"],
  help:["Hər suala 2–3 cümlə. Yalnız «yes/no» deyib dayanma."] },
{ id:"s09", level:"B1", part:"IELTS Part 1", prep:0, secs:30, ielts:1, title:"Reading",
  q:["Do you like reading?","What kind of things do you usually read?","Did you read a lot when you were a child?","Do you prefer paper books or e-books?"],
  help:["Zamanlara diqqət: usually (Simple), when I was a child (Past)."] },
// IELTS Part 2 (1 dəq hazırlıq, 2 dəqiqəyə qədər danışıq)
{ id:"s10", level:"B1", part:"IELTS Part 2", prep:60, secs:120, ielts:2, title:"A useful skill",
  q:["Describe a useful skill you learned.\nYou should say:\n– what the skill is\n– when and how you learned it\n– how often you use it\nand explain why this skill is useful to you."],
  help:["Hazırlıqda 4 bəndə 3–4 açar söz yaz.","Keçmiş (how you learned) → indi (how often) → səbəb (why)."] },
{ id:"s11", level:"B1", part:"IELTS Part 2", prep:60, secs:120, ielts:2, title:"A memorable journey",
  q:["Describe a journey you remember well.\nYou should say:\n– where you went\n– who you went with\n– what happened during the journey\nand explain why you remember it."],
  help:["Past Simple + Past Continuous; hisslər: I felt …, it was so … that …"] },
{ id:"s12", level:"B2", part:"IELTS Part 2", prep:60, secs:120, ielts:2, title:"A person who helped you",
  q:["Describe a person who has helped you in your studies or work.\nYou should say:\n– who this person is\n– how you know them\n– how they helped you\nand explain how you feel about this person."],
  help:["Present Perfect (has helped), nümunə hadisə, sonda hiss və səbəb."] },
// IELTS Part 3 (4–5 dəq, abstrakt müzakirə)
{ id:"s13", level:"B2", part:"IELTS Part 3", prep:0, secs:60, ielts:3, title:"Skills and education",
  q:["Which skills are most important for young people today?","Should schools teach practical skills like cooking or managing money?","How has technology changed the way people learn new skills?"],
  help:["Fikir + səbəb + nümunə + (istəyə görə) qarşı fikir: «On the other hand, some people argue …»"] },
{ id:"s14", level:"B2", part:"IELTS Part 3", prep:0, secs:60, ielts:3, title:"Travel and tourism",
  q:["Why do people enjoy travelling to other countries?","What problems can tourism cause for local people?","Will people travel more or less in the future? Why?"],
  help:["Ümumiləşdir: «Generally speaking …», «It depends on …», proqnoz: «I expect that …»"] }
];
const SPEAK_CRIT = [
  ["Fluency and Coherence","Uzun fasilələr olmadan danışdımmı? Fikirlər ardıcıl idi, bağlayıcılar (because, so, however) işlətdim?"],
  ["Lexical Resource","Mövzuya uyğun sözlər tapa bildim? Bilmədiyim sözü başqa sözlə izah etdim?"],
  ["Grammatical Range and Accuracy","Zamanlar düz idi? Sadə və mürəkkəb cümlələr qarışıq idi?"],
  ["Pronunciation","Yazını dinləyəndə özüm aydın başa düşürəm? (Tətbiq tələffüzü ölçmür — bunu yalnız sən və ya müəllim qiymətləndirə bilər.)"]
];
